version: '3'

services:

  web-app:
    build: ./web-app/
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=development
    depends_on:
      - db

  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: yourusername
      POSTGRES_PASSWORD: yourpassword
      POSTGRES_DB: yourdbname
    volumes:
      - ./database:/var/lib/postgresql
    ports:
      - 5444:5432

  adminer:
    image: adminer
    restart: unless-stopped
    ports:
      - 8031:8080
