from flask import Flask, send_file
import subprocess
import os

app = Flask(__name__)

@app.route('/')
def index():
    return 'Hello, visit /render to render the LaTeX file.'

@app.route('/render')
def render_latex():
    # Use the existing .tex file
    tex_file = 'CV-en_20220622.tex'

    try:
        subprocess.run(['pdflatex', tex_file], check=True)
        subprocess.run(['pandoc', tex_file, '-s', '--metadata', 'title="MyCV"', '-o', 'temp.html'], check=True)
    except subprocess.CalledProcessError:
        return 'Failed to compile LaTeX or convert to HTML'

    # Delete auxiliary files generated by LaTeX
    for ext in ['.aux', '.log', '.pdf']:
        os.remove(f'{tex_file.split(".")[0]}{ext}')

    # Read the HTML content and send it as the response
    with open('temp.html', 'r') as f:
        html_content = f.read()

    # Remove the temporary HTML file
    os.remove('temp.html')

    return html_content



if __name__ == '__main__':
    app.run(host='0.0.0.0', port=5000)
